name: Push Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths:
      - '*.tex'

env:
  AUTO_TAG: latest
  AUTO_TITLE: Latest Build
  TECTONIC_BUILD_PATH: tectonic-build

jobs:
  push_build:
    name: Push Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Tectonic
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-tectonic
        with:
          path: |
            ~/.cache/Tectonic
            ${{ env.TECTONIC_BUILD_PATH }}
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('.github/workflows/pushBuild.yml') }}

      - name: Install Tectonic
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev cargo
          cargo install tectonic --target-dir ${{ env.TECTONIC_BUILD_PATH }}

      - name: Build
        run: tectonic Li_Stephen_Resume.tex

      - name: Update Latest Build Release
        id: update_latest
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_release_tag: ${{ env.AUTO_TAG }}
          auto_release_title: ${{ env.AUTO_TITLE }}
          is_prerelease: false

      - name: Upload Asset to Latest Build Release
        uses:  Trinovantes/action-release-upload@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.update_latest.outputs.release_id }}
          upload_url: ${{ steps.update_latest.outputs.upload_url }}
          files: ./*.pdf
