name: Push Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths:
      - '*.tex'

jobs:
  pushBuild:
    name: Push Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Tectonic
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev cargo
          cargo install tectonic

      - name: Build
        run: tectonic Li_Stephen_Resume.tex

      - name: Update Latest Build Release
        id: update_latest
        uses: Trinovantes/action-automatic-release@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_release_tag: latest
          auto_release_title: Latest Build
          is_prerelease: false

      - name: Upload Asset to Latest Build Release
        uses:  Trinovantes/action-release-upload@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.update_latest.outputs.release_id }}
          upload_url: ${{ steps.update_latest.outputs.upload_url }}
          files: ./*.pdf
